import './globals.css'
import type {Metadata} from 'next'
import {Roboto} from 'next/font/google'
import React from "react";

const roboto = Roboto({
    adjustFontFallback: false,
    display: "swap",
    style: ['normal', 'italic'],
    weight: ['100', '300', '400', '500', '700', '900'],
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Car Rental Website',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
        shortcut: '/favicon.ico',
        apple: '/favicon.ico',
    },
    manifest: '/site.webmanifest',
    viewport: {
        width: 'device-width',
        initialScale: 1,
    },
    generator: 'Next.js',
    applicationName: 'Car Rental Website',
    referrer: 'origin-when-cross-origin',
    keywords: [
        'Car Rental Website',
    ],
    authors: [
        {name: 'Car Rental Website', url: 'https://example.com'},
        {name: 'MURAGEH', url: 'https://www.murageh.co.ke/'},
    ],
    colorScheme: 'light',
    creator: 'Car Rental Website',
    publisher: 'Car Rental Website',
    formatDetection: {
        email: false,
        address: false,
        telephone: false,
    }
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={roboto.className}>{children}</body>
        </html>
    )
}
